uploads = []

[[generated]]
id = "B7bcO1obeYS7LrOZGJY83"
uri = "file://artifacts/eduflow/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "PN4vZpsWTb1cfyNRI18NM"
uri = "file://artifacts/eduflow/dist.zip"
type = "unspecified"
title = "EduFlow web - yangi versiya (Vercel uchun)"

[[outputs]]
id = "WsQ6OM5hS0toUuxf8FFnS"
uri = "file://eduflow-source.zip"
type = "unspecified"
title = "EduFlow Source Code (APK uchun)"
