uploads = []

[[generated]]
id = "B7bcO1obeYS7LrOZGJY83"
uri = "file://artifacts/eduflow/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "PN4vZpsWTb1cfyNRI18NM"
uri = "file://artifacts/eduflow/dist.zip"
type = "unspecified"
title = "EduFlow web - yangi versiya (Vercel uchun)"

[[outputs]]
id = "WsQ6OM5hS0toUuxf8FFnS"
uri = "file://eduflow-source.zip"
type = "unspecified"
title = "EduFlow Source Code (APK uchun)"

[[outputs]]
id = "0sPxd4Kkl011vPC0duVRe"
uri = "file://artifacts/eduflow/eduflow-vercel.zip"
type = "unspecified"
title = "EduFlow – Vercel uchun to'g'ri ZIP"
